name: Build
on:
  workflow_dispatch:
  push:
    branches: "master"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build with py2exe
      - working-directory: app
        run: |
          pip install py2exe
          python setup.py py2exe
