name: Build
on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
jobs:
  build:
    runs-on: ["windows-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Build with py2exe
        run: |
          pip install py2exe
          cd app
          python setup.py py2exe
  publish:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Publish
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
      - name: Commit
        run: |
          git config --global user.name 'TurnipGuy30'
          git config --global user.email 'ba004629@bac.qld.edu.au'
          git commit -am "Automated report"
          git push
