name: Build
on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build with py2exe
        run: |
          pip install py2exe
          cd app
          python setup.py py2exe
