name: Build
on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
jobs:
  build:
    runs-on: ["windows-latest"]
    steps:
      - name: Build with py2exe
        uses: actions/checkout@v2.4.0
      - run: |
          pip install py2exe
          cd app
          python setup.py py2exe
  publish:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Publish
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
