name: Issue Opened
on:
  issues:
    types: ["opened", "reopened"]
jobs:
  open:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Create Project Card Action
        uses: technote-space/create-project-card-action@v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          PROJECT: Issue Management
          COLUMN: Open
          CHECK_ORG_PROJECT: true
